const model = [
    {
        "name":"monza-sp2.png",
        "src":"./img/index/monza-sp2.png"
    },
    {
        "name":"portofino.png",
        "src":"./img/index/portofino.png"
    },
    {
        "name":"purosangue.png",
        "src":"./img/index/purosangue.png"
    },
    {
        "name":"roma.png",
        "src":"./img/index/roma.png"
    },
    {
        "name":"roma-spider.png",
        "src":"./img/index/roma-spider.png"
    },
    {
        "name":"sf90-stradale.png",
        "src":"./img/index/sf90-stradale.png"
    },
    {
        "name":"296_gts.png",
        "src":"./img/index/296_gts.png"
    },
    {
        "name":"296-gtb.png",
        "src":"./img/index/296-gtb.png"
    },
    {
        "name":"812-competizione.png",
        "src":"./img/index/812-competizione.png"
    },
    {
        "name":"812-competizionet.png",
        "src":"./img/index/812-competizionet.png"
    },
    {
        "name":"812-gts.png",
        "src":"./img/index/812-gts.png"
    },
    {
        "name":"daytona-sp3.png",
        "src":"./img/index/daytona-sp3.png"
    },
    {
        "name":"df90-spider.png",
        "src":"./img/index/df90-spider.png"
    },
    {
        "name":"monza-sp1.png",
        "src":"./img/index/monza-sp1.png"
    },
]
export default model;